# Generated by Django 3.0.8 on 2020-07-30 18:09

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(choices=[('lni-cog', 'Engine'), ('lni-stats-up', 'Graphics'), ('lni-users', 'Users'), ('lni-layers', 'Layers'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket')], max_length=15, verbose_name='Icon')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('bio', models.CharField(max_length=100, verbose_name='Biography')),
                ('image', stdimage.models.StdImageField(upload_to='team', verbose_name='Image')),
                ('facebook_icon', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter_icon', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram_icon', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
