# Generated by Django 3.0.8 on 2020-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200730_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Laptop-Phone'), ('lni-cog', 'Cog'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers')], max_length=19, verbose_name='Icon')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('lni-cog', 'Cog'), ('lni-stats-up', 'Stats-Up'), ('lni-users', 'Users'), ('lni-layers', 'Layers'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket')], max_length=15, verbose_name='Icon'),
        ),
    ]
