# Generated by Django 3.0.8 on 2020-07-31 18:22

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200731_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Other Image',
                'verbose_name_plural': 'Other Images',
            },
        ),
    ]
